### PR TITLE
packet drop resolution

### PR DESCRIPTION
**Pull request by amarsri28**
This patch is for resolving packet drop issue

### CODE REVIEW

**Review by gab-arrobo — APPROVED** [review]
+1

**Comment by gab-arrobo** [comment]
Hi @amarsri28, just to double check, have you run a test to verify correctness of the patch/PR?

**Comment by gab-arrobo** [comment]
@sureshmarikkannu, any thoughts/comments about this PR? Thanks!

**Review by sureshmarikkannu — APPROVED** [review]
looks good.

**Pull request merged**
